import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { KakaoLoginButton } from "~/components/domains";
import { withRouteGuard } from "~/hocs";

const LoginPage: NextPage = withRouteGuard({ UNCONNECTED: true }, "/", () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <KakaoLoginButton
        restApiKey={
          process.env.NEXT_PUBLIC_KAKAO_APP_KEY_REST_API_KEY as string
        }
        redirectUri={process.env.NEXT_PUBLIC_KAKAO_LOGIN_REDIRECT_URI as string}
      >
        카카오 로그인하기
      </KakaoLoginButton>
    </div>
  );
});

export default LoginPage;
